### ISSUE TITLE
Need a readme file

### ISSUE THREAD

**Issue by iamReinir** [iamReinir/AzureTank#1]
# Add readme

Cần một file readme để introduction cho dự án và để deploy lên github page.
Nội dung sẽ dựa trên file doc template: 
Link doc : [AzureTank_doc](https://docs.google.com/document/d/1-3fQ3Id9IKlCrbFlW7En2cGUvNSsxDZp/edit?usp=sharing&ouid=116915821849323227886&rtpof=true&sd=true)

Sẽ cần:
Title, introduction and detail description, auxiliary documentation, and maybe download link

Sau khi xong thì @iamReinir sẽ deploy nó lên github page -> đóng issue

**Comment by 2bngbtran04** [comment]
Test issue

**Comment by 2bngbtran04** [comment]
@iamReinir jfjfjfjfjf

**Comment by iamReinir** [comment]
Nhờ @Dungnguyengl làm cái này, dựa trên doc template của mình nha. Phần download link thì từ từ cũng được.

**Comment by Dungnguyengl** [comment]
Due date là khi nào nhỉ @iamReinir

**Comment by iamReinir** [comment]
@Dungnguyengl due ngày 28/05 nha

**Comment by 2bngbtran04** [comment]
Trân đề xuất thêm base trên ý tưởng README file của Dũng nhé:

 AzureTank

 Introduction
AzureTank is an offline game where players control a tank and must destroy shapes and opponents to level up, upgrade their tank, and gain new capabilities. It is a 2D shooting game with a top-down view, where players collect items dropped by enemies and engage in combat inspired by historical war events of Vietnam.

 Game Features
- Genre: 2D shooting with top-down perspective.
- Objective: Destroy shapes and opponents, collect items, level up, and upgrade the tank.
- Historical Context: The plot includes elements based on historical war events of Vietnam.
- Varied Gameplay: Different gameplay modes to keep the player engaged and prevent monotony.
  
 FAQ

Technical used:
-	C#
-	Unity
-	……….

 How do I install?
[Installation instructions here]

 How to play it?
[Gameplay instructions here]

 About Us
- iamReinir: Project Manager, Developer Support, Music Designer
- CanhTruongKool: Developer
- Bùi Ngọc Bảo Trân: Document Manager, Support Design Story
- Arthur Cap: Graphic Designer
- Phạm Ngọc Quyền: Tester
- Nguyễn Dũng: Developer
- dongloi2504: Gameplay Designer, Story Designer



To: @Dungnguyengl  @iamReinir 
cc: @dongloi2504

**Comment by dongloi2504** [comment]
đổi lại PM là tui nha @2bngbtran04

**Comment by 2bngbtran04** [comment]
Ok nhe

**Comment by Dungnguyengl** [comment]
@iamReinir @2bngbtran04 t đã update nhờ mn review giúp
