### ISSUE TITLE
Tìm kiếm âm thanh cho bắn súng- bom nổ

### ISSUE THREAD

**Issue by dongloi2504** [iamReinir/AzureTank#11]
@Dungnguyengl  tìm âm thanh cho súng bắn- bom nổ
deadline: 27-5 -> 30-5 
tìm càng nhiều âm thanh càng tốt để chia cho team địch và team ta

**Comment by Dungnguyengl** [comment]
Đã nhận thông tin

**Comment by 2bngbtran04** [comment]
Trân thấy OKe rồi nha Dũng

To: @Dungnguyengl @dongloi2504

**Comment by dongloi2504** [comment]
Duyệt nha Dũng
To: @Dungnguyengl

**Comment by dongloi2504** [comment]
Có thể sẽ tạo issue về âm thanh nếu như cảm thấy âm thanh ko hợp

**Comment by Dungnguyengl** [comment]
@2bngbtran04 @dongloi2504  review cái PR giúp vs các cậu
