### ISSUE TITLE
Generate bom rơi out of nowhere 

### ISSUE THREAD

**Issue by dongloi2504** [iamReinir/AzureTank#12]
Deadline: 27-5 -> 30-5

**Comment by CanhTruongKool** [comment]
@dongloi2504  @iamReinir  @Dungnguyengl  Review MR https://github.com/iamReinir/AzureTank/pull/21 để done issue nào

**Comment by iamReinir** [comment]
PR nè : https://github.com/iamReinir/AzureTank/pull/22
@CanhTruongKool thả lộn issue rồi

**Comment by iamReinir** [comment]
Fix nhánh theo rule mới + fix conflict : https://github.com/iamReinir/AzureTank/pull/25
