### ISSUE TITLE
Viết code Unity game

### ISSUE THREAD

**Issue by dongloi2504** [iamReinir/AzureTank#13]
Deadline: 28-5-2024 -> 30-5-2024
hết máu thì chết hoặc địch bị bắn trúng 3 phát thì chết , nhặt cái gì đó (coi như tượng trưng cho tim) cũng được để hồi máu
close issue sau  mr đã merge

**Comment by CanhTruongKool** [comment]
@dongloi2504 @Dungnguyengl @iamReinir review MR https://github.com/iamReinir/AzureTank/pull/21 để done issue nào
