### ISSUE TITLE
Viết cốt truyện cho chapter 1 

### ISSUE THREAD

**Issue by dongloi2504** [iamReinir/AzureTank#15]
deadline 27-5 -> 1-6
đóng trong 1 file StoryTank.txt trong thư mục Story
Pr vào main
Close issue sau khi cốt truyện đã được duyệt và đóng vào thư mục Story

**Comment by 2bngbtran04** [comment]
Theo thống nhất lại thì con game đợt này mình sẽ làm 1 giai đoạn thôi.
- Trong giai đoạn đấy có 5 trận đánh lớn tương ứng với 5 màn chơi nhóe !!!

To: @dongloi2504  @pnquyen24

**Comment by 2bngbtran04** [comment]
Tui đã hoàn thành Story của lv3, lv4, lv5 ùi
- Link: [Story](https://drive.google.com/drive/folders/1bNbNj6_Ecqdw-zpqG-49YD6Uz2PdZaC6?usp=sharing)

Review rồi comment giúp tui nha

To: @dongloi2504  @pnquyen24
