### ISSUE TITLE
Viết nhanh code về mìn

### ISSUE THREAD

**Issue by dongloi2504** [iamReinir/AzureTank#17]
30-5 -> 31-5
tương tự máu nhưng lần này thì khi chạm vào nó sẽ bị mất máu nhé
close issue sau  mr đã merge

**Comment by CanhTruongKool** [comment]
@dongloi2504  @Dungnguyengl  @iamReinir  review MR  https://github.com/iamReinir/AzureTank/pull/21 để done issue nào

**Comment by iamReinir** [comment]
Check review comment nha @CanhTruongKool
