### ISSUE TITLE
Prototype#1 - Player, Enemies, Shoot, Control

### ISSUE THREAD

**Issue by iamReinir** [iamReinir/AzureTank#2]
# The bare minimum for the game to be playable. 

This include:
- Having the main character move
- Control the shooting direction with the mouse, and shooting
- Enemies with rudimentary AI (might lack the effort to do this)

All assets will be placeholders.

**Comment by iamReinir** [comment]
ở nhánh 'trung' đã có code cơ bản, có thể di chuyển, bắn, xử lí va chạm với đạn.

**Comment by iamReinir** [comment]
check code nha mng. PR : https://github.com/iamReinir/AzureTank/pull/16

**Comment by dongloi2504** [comment]
đã check, tạm ổn, cần nâng cấp IQ cho AI

**Comment by iamReinir** [comment]
PR Merged
