### ISSUE TITLE
Hoàn thành Template Doc của PRU212

### ISSUE THREAD

**Issue by iamReinir** [iamReinir/AzureTank#3]
# Hoàn thành template Doc của PRU212

Hoàn thành template để nộp thầy, muộn nhất là ngày 17/05.

Link doc :[AzureTank_Doc](https://docs.google.com/document/d/1-3fQ3Id9IKlCrbFlW7En2cGUvNSsxDZp/edit?usp=sharing&ouid=116915821849323227886&rtpof=true&sd=true)

Email thầy Vịnh : vinhnv27@fe.edu.vn

**Comment by 2bngbtran04** [comment]
OKe nhóe, tối nay xong trước 21h, có gì mn vào check nhé !!!

**Comment by 2bngbtran04** [comment]
- Trân đã rì viu xong 1 lượt, có bỏ 1 số chỗ không tương thích với trò chơi của nhóm.
- Nội dung của doc mô tả khá kĩ về các MODULES cũng như mô tả YÊU CẦU của trò chơi. Nên nhóm làm thiên về Tech đọc kĩ để nắm + thấy Modules nào nhóm mình gánh không nổi thì đề xuất bỏ trước chứ nộp rồi thì khó bỏ.

Xong nha, @iamReinir 
cc: @Dungnguyengl  @Arthur-Cap

**Comment by iamReinir** [comment]
Tui ok nha. Ko có vấn đề gì thì tầm 9h tui gửi thầy @2bngbtran04, @Arthur-Cap, @Dungnguyengl

**Comment by 2bngbtran04** [comment]
Oke @iamReinir  nhóe

**Comment by 2bngbtran04** [comment]
[
[Group 2 - Project Document.pdf](https://github.com/iamReinir/AzureTank/files/15329009/Group.2.-.Project.Document.pdf)
](url)

Done :))

**Comment by iamReinir** [comment]
Đã mail thầy, đóng issue nhá
