### ISSUE TITLE
Layout màn hình : main menu, pause, endgame 

### ISSUE THREAD

**Issue by iamReinir** [iamReinir/AzureTank#4]
# Layout màn hình : main menu, pause, endgame 

Giao diện cơ bản cho 3 màn hình này.

## Main menu
- Start Game
- Setting
- Quit

## Pause
- Continue
- Setting
- To main menu

## Endgame
- Show score
- To main menu

Ưu tiên có layout trước, mockup cũng được. Có code thì tốt.

**Comment by Arthur-Cap** [comment]
.

**Comment by Arthur-Cap** [comment]
![Screenshot 2024-05-20 113643](https://github.com/iamReinir/AzureTank/assets/125182326/84afae7c-f4b1-40b5-a44c-d46cf83b6c63)
![Screenshot 2024-05-20 113621](https://github.com/iamReinir/AzureTank/assets/125182326/dd6df71e-2aa7-42ed-82d1-233f85b8627a)
![01 (2)](https://github.com/iamReinir/AzureTank/assets/125182326/e9498dd3-32d2-4b67-b999-c7ad3946ff24)
![7e3c5e58-9517-4767-840b-cc07fb1a6b8a](https://github.com/iamReinir/AzureTank/assets/125182326/b39218dc-a560-4409-977d-7ba1e514e9d0)

**Comment by Arthur-Cap** [comment]
https://www.canva.com/design/DAGFuqA4heE/M5NVt8WTV6jnaOuolLG1GA/edit

**Comment by iamReinir** [comment]
@Arthur-Cap ông làm cái này trong unity đc ko ô?
Phần menu mở đầu thôi
