### ISSUE TITLE
Chuyển map, và bắn đạn qua nước

### ISSUE THREAD

**Issue by dongloi2504** [iamReinir/AzureTank#40]
có tất cả 6 map khiến cho xe tank di chuyển từ map 1 -> 6 . Nếu cảm thấy bắn qua nước khó quá thì sẽ kéo dài thời gian sang 13/6. Bàn với Lợi nếu như cần thay đổi lại title pallate cho river

**Comment by dongloi2504** [comment]
9/6 -> 10/6

**Comment by iamReinir** [comment]
PR chỉ có đổi map. cần thêm thời gian để sửa lại bullet.
@dongloi2504 
bro sửa đống collider của map pls

**Comment by iamReinir** [comment]
nhờ @CanhTruongKool , @Dungnguyengl , @Arthur-Cap  review PR
