### ISSUE TITLE
Ý tưởng storyline cho game.

### ISSUE THREAD

**Issue by iamReinir** [iamReinir/AzureTank#5]
# Một ý tưởng cho storyline

Viết dưới format markdown, đặt trong thư mục story/(the idea).md
Nếu readme.md xong thì link vào.

**Comment by 2bngbtran04** [comment]
- Trân đã tạo file (the idea).md chứa trong folder story và update story của lv3, lv4, lv5 rồi.
- Đã push lên branch "Story"
- Chưa pull request với chưa link vào file README (Vì file README chưa được approve).
- Nhờ Trung + Lợi review giúp nhé

To: @iamReinir  @dongloi2504  @pnquyen24

**Comment by dongloi2504** [comment]
@2bngbtran04  cái ReadMe tui ko có quyền aprrove :v. để hối trung prove readme cho

**Comment by dongloi2504** [comment]
![image](https://github.com/iamReinir/AzureTank/assets/142334813/12440528-1ad8-4b3a-9533-df2cb1c378a9)
ko coi được readme nên ko đánh giá được gì

**Comment by 2bngbtran04** [comment]
Đấy là Drive gì vậy Lợi, tui đâu có xóa cái đó đâu ?? @dongloi2504

**Comment by 2bngbtran04** [comment]
Lợi vào Branch tên Story rồi có folder story á, hqua tui push lên đấy r. @dongloi2504

**Comment by 2bngbtran04** [comment]
Đây nè @dongloi2504  ơi

![image](https://github.com/iamReinir/AzureTank/assets/145552140/937ec3c9-70f9-47bd-b7a9-2db56db4ffcf)
