### ISSUE TITLE
Viết Report #2 - Project Management Plan

### ISSUE THREAD

**Issue by iamReinir** [iamReinir/AzureTank#7]
# Report 2 - Project Management Plan

Hoàn thiện D2 trong Rubric. 

![image](https://github.com/iamReinir/AzureTank/assets/92148213/a568f5f9-9612-4ca4-9350-82f7b3266fe0)

**Comment by iamReinir** [comment]
Nhờ @dongloi2504  support Trân làm cái này. T6 deadline

**Comment by 2bngbtran04** [comment]
Ủa cái này có template hong z @iamReinir  ơi ??

**Comment by 2bngbtran04** [comment]
Bởi vì không có Template nên Trân tự viết luôn.
- Link: [D2](https://docs.google.com/document/d/1-3fQ3Id9IKlCrbFlW7En2cGUvNSsxDZp/edit?usp=sharing&ouid=116915821849323227886&rtpof=true&sd=true)

Nhờ @iamReinir  check giúp như vậy đã ổn chưa nhé

To: @iamReinir 
cc: @dongloi2504

**Comment by dongloi2504** [comment]
![image](https://github.com/iamReinir/AzureTank/assets/142334813/223ef85f-6726-4476-a6c1-26c0d6addbb8)
đọc sơ qua thấy cái này hình như hơi sai :v thấy hướng làm có vẻ là game offline và single player hơn

**Comment by 2bngbtran04** [comment]
Ok nha, có j Lợi cứ comment vào doc. Khi nào xong thì hú tuôi nhé

To: @dongloi2504 
cc: @iamReinir

**Comment by 2bngbtran04** [comment]
Trân đã review xong một lượt D2 rồi. Nhờ Lợi check lại lần nữa và Trung confirm giúp nhé.
- Confirm trước 3h chiều nay để Trân format rồi nhờ Trung gửi đi nhé !!

To: @dongloi2504  @iamReinir

**Comment by iamReinir** [comment]
@2bngbtran04 ơi nay bận tới tối lận (chắc tầm 10h) nên tui review muộn xíu nha

**Comment by 2bngbtran04** [comment]
Oke nha @iamReinir , miễn sao gửi trong hôm nay là được đúng hong ??

**Comment by iamReinir** [comment]
@2bngbtran04  @dongloi2504  phần cốt truyện viết như thế là ko đổi ý được nha. Nếu commit được phần này thì tui ok.

**Comment by 2bngbtran04** [comment]
Chốt xong nội dung, Trân format doc nhé @iamReinir  !!

To: @iamReinir  @dongloi2504

**Comment by 2bngbtran04** [comment]
Trân đã format xong, nhờ Trung gửi bài qua thầy giúp nhé 
- Link bài pdf: [D2_AzureTank](https://drive.google.com/file/d/1RPRNtc6dNCYbdoNiTmaFnedWt6YHPKn1/view?usp=sharing)

To: @iamReinir  @dongloi2504

**Comment by iamReinir** [comment]
Đã gửi thầy nha @2bngbtran04
