### ISSUE TITLE
Viết Report #3 - Software Requirement Speficication 

### ISSUE THREAD

**Issue by iamReinir** [iamReinir/AzureTank#8]
#Viết Report 3 - Software Requirement Speficication 

![image](https://github.com/iamReinir/AzureTank/assets/92148213/a825e446-636c-4606-8863-4c98b0b3b740)

**Comment by 2bngbtran04** [comment]
Trân có fix lại D3 theo comment của Lợi rồi, nhờ Lợi với Trung review lại round nữa rồi Trân format nhé

- Link: [Link](https://docs.google.com/document/d/1-LI4-mRlfO601z15eC-5u1bCxrwymb_DeEp4jf6x_kA/edit?usp=sharing)

@iamReinir  @dongloi2504

**Comment by 2bngbtran04** [comment]
Trân đã up bản pdf final rồi nhé. Nhờ Trung hoặc Lợi nộp thầy trong hôm nay (T6,7/6)

Link: [https://drive.google.com/file/d/1NGy4LaHpHSmwcwLGy9YijapbiMnTCsy1/view?usp=drivesdk](https://drive.google.com/file/d/1NGy4LaHpHSmwcwLGy9YijapbiMnTCsy1/view?usp=drivesdk)

@iamReinir @dongloi2504

**Comment by iamReinir** [comment]
@2bngbtran04 tui ok nha. Đã gửi thầy
