### ISSUE TITLE
Tạo UI cho 2 xe tank ta và địch

### ISSUE THREAD

**Issue by dongloi2504** [iamReinir/AzureTank#9]
3 ngày để làm 27-5 -> 30-5
@pnquyen24

**Comment by Arthur-Cap** [comment]
![image](https://github.com/iamReinir/AzureTank/assets/125182326/46dd131f-2813-4dbf-b9f6-6038533d09e9)

**Comment by Arthur-Cap** [comment]
![Uploading Picsart_24-05-28_08-30-40-339.png…]()

**Comment by Arthur-Cap** [comment]
![Picsart_24-05-27_14-33-46-210](https://github.com/iamReinir/AzureTank/assets/125182326/7161f37f-447c-4065-8705-388726303826)

**Comment by Arthur-Cap** [comment]
![Uploading Picsart_24-05-28_08-30-40-339.png…]()

**Comment by Arthur-Cap** [comment]
![Picsart_24-05-28_08-30-40-339](https://github.com/iamReinir/AzureTank/assets/125182326/2ab9d57c-ec99-4ca8-abf9-661dfcaabad0)
![Picsart_24-05-27_14-33-46-210](https://github.com/iamReinir/AzureTank/assets/125182326/593c347a-3183-4a60-a034-1cfb999d1def)

**Comment by Arthur-Cap** [comment]
![Picsart_24-05-28_08-39-00-535](https://github.com/iamReinir/AzureTank/assets/125182326/13be3387-1b4c-4efc-be61-703baab47237)
![Picsart_24-05-27_14-33-46-210](https://github.com/iamReinir/AzureTank/assets/125182326/473041ae-70f4-41b7-ba61-35fd3170aeb5)

**Comment by iamReinir** [comment]
Có ba ý:
1. Đổ bóng (shadow) => bỏ nó đi, lúc xe tăng nó quay nhìn kỳ lắm.
2. Tách súng với thân ra. Nòng súng quay độc lập với thân 
3.  Cái sprite vẫn là sprite nhìn xéo từ trên xuống. => cố gắng chuyển hướng nhìn thành vuông góc với mặt đất.
Nhờ @Arthur-Cap check nha.

**Comment by dongloi2504** [comment]
![image](https://github.com/iamReinir/AzureTank/assets/142334813/a60aadff-802c-4a58-b72d-48d065e5e501)
cái này được ko @iamReinir

**Comment by iamReinir** [comment]
được nhưng mà lấy cái sprite ra thành transparent png nha
Tách súng với thân nữa

**Comment by Arthur-Cap** [comment]
lấy của Lợi đi cho tiện, toàn ảnh AI gen nên khó kiểm soát lắm :v

**Comment by iamReinir** [comment]
Ấy cái của Lợi vẫn bị đổ bóng

**Comment by Arthur-Cap** [comment]
chịu khó thôi, thu nhỏ lại không ai để ý đâu, hoặc Lợi sửa lại prompt xem sao

**Comment by dongloi2504** [comment]
@iamReinir 

![image](https://github.com/iamReinir/AzureTank/assets/142334813/cd80b7aa-d39a-4f92-9403-08aa0126e720)
update tank

**Comment by dongloi2504** [comment]
![image](https://github.com/iamReinir/AzureTank/assets/142334813/abd50ecf-acaf-4fea-b728-a7eeb71be8da)
và đây là xe tank boss final :))

**Comment by dongloi2504** [comment]
![image](https://github.com/iamReinir/AzureTank/assets/142334813/d3ce69de-1948-49d7-9721-77a2183bd2fa)
xe tank lính của địch nếu được duyệt XD

**Comment by iamReinir** [comment]
1. cắt ra thành transparent png nha @dongloi2504 , để vậy ko bỏ vào unity đc
2. Tách súng với thân ra. Do bọn nó quay độc lập với nhau
